sudo: required

services:
  - docker

language: python

python:
  - "3.6"

before_install:
  # Download Cromwell
  - wget -O $TRAVIS_BUILD_DIR/cromwell-42.jar https://github.com/broadinstitute/cromwell/releases/download/42/cromwell-42.jar;
  - curl -o requirements.txt "https://dockstore.org/api/metadata/runner_dependencies?client_version=1.6.0&python_version=3"

install:
  - pip install -r requirements.txt

script:
  - docker build -t test-image -f checker/Dockerfile checker
  - >-
    sed 's/dockerPull:.*/dockerPull: test-image:latest/g' checker/md5sum-checker.cwl
  - >-
    sed 's/docker:.*/docker: "test-image:latest"/g' checker/md5sum-checker.wdl
  - python -m unittest discover -s .