sudo: required

services:
  - docker

language: python

python:
  - "3.6"

before_install:
  # Download Cromwell
  - wget -O $TRAVIS_BUILD_DIR/cromwell-42.jar https://github.com/broadinstitute/cromwell/releases/download/42/cromwell-42.jar;
  - curl -o requirements.txt "https://dockstore.org/api/metadata/runner_dependencies?client_version=1.6.0&python_version=3"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -s .